### ISSUE TITLE
[question] Are save states going to be supported for cores that do not have that feature?

### ISSUE THREAD

**Issue by lutechsource** [golem-fpga/golem#21]
Looking at this update about save states ([https://github.com/golem-fpga/golem/pull/19](url)), the part that says "supported for now per-game in the database" has me curious. Does this mean that as long as a game rom is in this database, it's state can be saved regardless if the core doesn't support save states? 

I know the save states don't load properly yet, but is the plan to universally support save states even when the core doesn't?

**Comment by hansl** [comment]
Hi @lutechsource.

Unfortunately, this is not possible with the current tech. I'm not certain it won't be possible ever, but for now I will focus on the roadmap for the project.

For the record, the save states do load properly, it's the SD Card mounting that doesn't (the SAV files in MiSTer). I'm working on it right now.
